sudo: false
dist: xenial
language: python
python:
  - 3.8
  - 3.7
  - 3.6
cache: pip
env:
  matrix:
    - DJANGO='>=3.0,<3.1'
    - DJANGO='>=2.2,<3.0'
    - DJANGO='>=2.1,<2.2'
    - DJANGO='>=2.0,<2.1'
    - DJANGO='>=1.11,<1.12'
matrix:
  fast_finish: true
  exclude:
    - python: 3.8
      env: DJANGO='>=1.11,<1.12'
    - python: 3.7
      env: DJANGO='>=1.11,<1.12'
install:
  - pip install flake8 coverage django$DJANGO -e .
script:
  - flake8
  - coverage run tests/manage.py test django_python3_ldap
after_success:
  - coverage report
deploy:
  provider: pypi
  user: etianen
  password:
    secure: e6HaAoVTzvCuBGLk9gkPxMgzYHS/HB7TLxZaqvicVIKRRl9IOGfyNzufU4wa8kUAN0YlDnFk6SYVn2bpsQoctKGWCFdo9BFGOpayGcllrF8ONa+HnB0g9rnu0kRluGeH7SZG7MVJoWYaIKG/MAUUtlxl9uwC2zaO8Cq4zASrJgI=
  on:
    tags: true
    condition: $DJANGO = '>=3.0,<3.1'
    python: 3.8
    repo: etianen/django-python3-ldap
  distributions: sdist
notifications:
  email: false
