language: python
sudo: false
python:
  - 3.2
  - 3.3
  - 3.4
env:
  matrix:
    - DJANGO=django==1.7.3
  global:
    # LDAP_AUTH_URL
    - secure: "YNnYSUnzs5XPS+f8sV0f4nTK/nmjgA2LUFIEznkI3b9F/d41w2RhvCI+S6cCo7VX8POdomUSKpIjWobBdQKWbO2nq7vsgjJdkSX0d9Wy19eiwSADSOALpuMbDMGXp9uI3H6mC3oPKES1upTaPKdpPQwa/8+7+h5QorEt2gHlZH0="
    # LDAP_AUTH_SEARCH_BASE
    - secure: "XITGh+4ssRZYa6odUhFhy8K2AY6P5aG8B7ZAtYeQYxeuW9Utd7xC++PxT+GJiu0xDIxxE2f5hjXZNERV0dI6y/9rc1y9r9G1GKadIAhDj4w2r3cP/2vZFeAnwpEjx5RqnWYoMYPwWfViOBVDjzuLYjwekKRIyZVcCw9es1xa6HM="
    # LDAP_AUTH_TEST_USER_USERNAME
    - secure: "WAr3C+Cp/FAcIOqbkV6WLxuvk1mjEOy3I1/uQLNDSunGI4LdX3qCldDY+mPTzhobiMJ1HenJOwquS5qnF2tmDBUlLzGkZCvEXPQQMXrzvZFBTspvSMC//BB7nF7WhqyObxZuZiiWUDM0wXdaFV5EA6LlUWRhCYtKPfMVbCpbmK8="
    # LDAP_AUTH_TEST_USER_PASSWORD
    - secure: "GP/Dry1ed/km5UDjUBT09fom6wq/165U8VeRvce8/D8fG8Jp92bMIlToAjXw0Lm4LcreA3Te5ErqogpDXG2mzof+st8kjwnThU0gGBe631F+CCKYCpo4EdmlMuQYDWTfi4IBxBGqfx7Ac/dxlidNN9X0qK7xgrECKudPA+6DGZg="
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - travis_retry pip install $DJANGO coverage --download-cache $HOME/.pip-cache
  - pip install -e . --download-cache $HOME/.pip-cache
script: 
  - coverage run tests/manage.py test django_python3_ldap
after_script:
  - coverage report
notifications:
  email: false
