language: python
sudo: false
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
env:
  matrix:
    - DJANGO=django==1.7.7
    - DJANGO=django==1.8
  global:
    # LDAP_AUTH_URL
    - secure: "cHd1s2qFbGzws7HI0u62Wr/Xqu+XyJnVnoFtstayFasNgBfkfUy78ihRTw3c6PxBSVU58hDL1OjNhBoH+t61AZ8BTU2khTLT36klSPnHB5e3FYJp8sxMm3HvSHxQSnRl8HgagUm9IAwWEuxLuJtOckidMkRfh3KdqDLqDMriHMU="
    # LDAP_AUTH_SEARCH_BASE
    - secure: "XITGh+4ssRZYa6odUhFhy8K2AY6P5aG8B7ZAtYeQYxeuW9Utd7xC++PxT+GJiu0xDIxxE2f5hjXZNERV0dI6y/9rc1y9r9G1GKadIAhDj4w2r3cP/2vZFeAnwpEjx5RqnWYoMYPwWfViOBVDjzuLYjwekKRIyZVcCw9es1xa6HM="
    # LDAP_AUTH_TEST_USER_USERNAME
    - secure: "WAr3C+Cp/FAcIOqbkV6WLxuvk1mjEOy3I1/uQLNDSunGI4LdX3qCldDY+mPTzhobiMJ1HenJOwquS5qnF2tmDBUlLzGkZCvEXPQQMXrzvZFBTspvSMC//BB7nF7WhqyObxZuZiiWUDM0wXdaFV5EA6LlUWRhCYtKPfMVbCpbmK8="
    # LDAP_AUTH_TEST_USER_PASSWORD
    - secure: "GP/Dry1ed/km5UDjUBT09fom6wq/165U8VeRvce8/D8fG8Jp92bMIlToAjXw0Lm4LcreA3Te5ErqogpDXG2mzof+st8kjwnThU0gGBe631F+CCKYCpo4EdmlMuQYDWTfi4IBxBGqfx7Ac/dxlidNN9X0qK7xgrECKudPA+6DGZg="
matrix:
  fast_finish: true
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - travis_retry pip install $DJANGO "coverage<4.0" --download-cache $HOME/.pip-cache
  - pip install -e . --download-cache $HOME/.pip-cache
script:
  - coverage run tests/manage.py test django_python3_ldap
after_script:
  - coverage report
notifications:
  email: false
